data_provider:
  data_aug:
    name: randaug erase
    n: 2
    m: 9
    p: 0.1
  base_batch_size: 4
  test_batch_size: 4
  n_worker: 8

net_config:
  name: b0
  dropout: 0
  
run_config:
  base_lr: 0.001
