data_provider:
  dataset: cityscapes
  data_dir:  /scratch/apicker/cityscapes/leftImg8bit/
  data_aug:
    name: randaug
    n: 1
    m: 3
  base_batch_size: 8
  n_worker: 8

run_config:
  n_epochs: 400
  base_lr: 0.00006
  warmup_epochs: 20
  warmup_lr: 0.0
  
  lr_schedule_name: cosine
  lr_schedule_param: {}
  optimizer_name: adamw
  optimizer_params:
    eps: 1.0e-08
    betas:
    - 0.9
    - 0.999
  weight_decay: 0.01
  no_wd_keys:
  - norm
  - bias
  
  
  
  grad_clip: 2.0
  mixup_config:
    op:
    - - mixup
      - 0.1
      - 1.0
    - - cutmix
      - 0.1
      - 1.0


backbone_drop:
  name: droppath
  drop_prob: 0.05
  linear_decay: true

